spring:
  application:
    name: library
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: none
  flyway:
    enabled: true
    locations: db/migration/structure, db/migration/data
    validate-on-migrate: true