CREATE TABLE genre
(
   id SERIAL PRIMARY KEY,
   nom VARCHAR(255) NOT NULL
);

CREATE TABLE livre (
   id SERIAL PRIMARY KEY,
   titre VARCHAR(255) NOT NULL,
   auteur VARCHAR(255) NOT NULL,
   genre_id INT,
   created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   modifed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   CONSTRAINT fk_genre FOREIGN KEY (genre_id) REFERENCES genre(id) ON DELETE SET NULL
);

CREATE TABLE emprunteur
(
    id SERIAL PRIMARY KEY,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modifed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE emprunt
(
     id SERIAL PRIMARY KEY,
     emprunteur_id INT NOT NULL,
     livre_id INT NOT NULL,
     debut DATE NOT NULL,
     fin DATE,
     created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     modifed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     CONSTRAINT fk_emprunteur FOREIGN KEY (emprunteur_id) REFERENCES emprunteur(id) ON DELETE CASCADE,
     CONSTRAINT fk_livre FOREIGN KEY (livre_id) REFERENCES livre(id) ON DELETE CASCADE
);